INSERT INTO category (name, description) VALUES ('Food','All kinds of food');
INSERT INTO category (name, description) VALUES ('Car','ALl things connected to car - such as gasoline, car wash, insurance, etc.');
INSERT INTO category (name, description) VALUES ('Flat','Bills, rent, loan installment, etc.');
INSERT INTO sub_category (name, description) VALUES ('Restaurant','all kind of restaurants');
INSERT INTO sub_category (name, description) VALUES ('Milk','Kind of white drink');
INSERT INTO sub_category (name, description) VALUES ('Sugar','Kind of white sand');
INSERT INTO sub_category (name, description) VALUES ('Gasoline','Drink for the car');
INSERT INTO sub_category (name, description) VALUES ('Insurance','OC/AC');
INSERT INTO sub_category (name, description) VALUES ('Rent','');
INSERT INTO sub_category (name, description) VALUES ('Loan installment','Rly hurt');
